import type { Metadata } from "next";
import { Quicksand, Noto_Sans_Thai } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Providers from "./providers";

const quicksandSans = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const notoSansThaiMono = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "โอสุ!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="osu-theme">
      <body
        className={`${quicksandSans.variable} ${notoSansThaiMono.variable} antialiased`}
      >
        <a className="skip-to-main-content-link animation-wrapper" href="#head-of-main-content" tabIndex={1}>
          <div className="animation-container">
            <div className="osu-animate-background"></div>
          </div>
          Skip to main content
        </a>
        <Header />
        <main id="app" tabIndex={-1}>
          <Providers>
            {children}
          </Providers>
        </main>
        <Footer />
      </body>
    </html>
  );
}
